services:
  - type: web
    name: bcc-enrollment
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://bcc-enrollment.onrender.com
      - key: ASSET_URL
        value: https://bcc-enrollment.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-db032megekts73805mcg-a.renderdb
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: bcc_enrollment
      - key: DB_USERNAME
        value: bcc_user
      - key: DB_PASSWORD
        value: TqrNxpV7Nnbyrttahzdt3g0pu5r48jCf

databases:
  - name: bcc-enrollment-db
    databaseName: bcc_enrollment
    user: bcc_user
    plan: free
