CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number VARCHAR(30) NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'student',
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_users_role CHECK (role IN ('student', 'registrar'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_student_number ON users(student_number);

CREATE TABLE IF NOT EXISTS programs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id INTEGER NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  department VARCHAR(120) NOT NULL,
  duration_years SMALLINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_programs_duration CHECK (duration_years BETWEEN 1 AND 6)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_programs_source ON programs(source_id);

CREATE TABLE IF NOT EXISTS program_majors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id INTEGER NOT NULL,
  source_id INTEGER NOT NULL,
  name VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_major_program FOREIGN KEY (program_id) REFERENCES programs(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT uq_program_major_source UNIQUE (program_id, source_id)
);

CREATE TABLE IF NOT EXISTS subjects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id INTEGER NOT NULL,
  major_id INTEGER NULL,
  source_id INTEGER NULL,
  code VARCHAR(40) NOT NULL,
  title VARCHAR(255) NOT NULL,
  units NUMERIC(3,1) NOT NULL,
  year_level SMALLINT NOT NULL,
  semester VARCHAR(8) NOT NULL,
  is_capstone BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_subject_program FOREIGN KEY (program_id) REFERENCES programs(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_subject_major FOREIGN KEY (major_id) REFERENCES program_majors(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ck_subject_units CHECK (units BETWEEN 1 AND 9),
  CONSTRAINT ck_subject_year_level CHECK (year_level BETWEEN 1 AND 6),
  CONSTRAINT ck_subject_semester CHECK (semester IN ('1st', '2nd', 'Summer'))
);

CREATE TABLE IF NOT EXISTS enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL,
  program_id INTEGER NOT NULL,
  major_id INTEGER NULL,
  school_year VARCHAR(9) NOT NULL,
  semester VARCHAR(8) NOT NULL,
  year_level SMALLINT NOT NULL,
  student_type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'submitted',
  registrar_note VARCHAR(500) NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_enrollment_program FOREIGN KEY (program_id) REFERENCES programs(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_enrollment_major FOREIGN KEY (major_id) REFERENCES program_majors(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT uq_student_term UNIQUE (student_id, school_year, semester),
  CONSTRAINT ck_enrollment_semester CHECK (semester IN ('1st', '2nd', 'Summer')),
  CONSTRAINT ck_enrollment_student_type CHECK (student_type IN ('New', 'Continuing', 'Transferee', 'Returning')),
  CONSTRAINT ck_enrollment_status CHECK (status IN ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'withdrawn'))
);

CREATE TABLE IF NOT EXISTS enrollment_subjects (
  enrollment_id INTEGER NOT NULL,
  subject_id INTEGER NOT NULL,
  PRIMARY KEY (enrollment_id, subject_id),
  CONSTRAINT fk_es_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_es_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS class_schedules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id INTEGER NOT NULL,
  subject_id INTEGER NOT NULL,
  school_year VARCHAR(9) NOT NULL,
  semester VARCHAR(8) NOT NULL,
  year_level SMALLINT NOT NULL,
  section VARCHAR(20) NOT NULL,
  instructor_name VARCHAR(160) NOT NULL,
  days VARCHAR(40) NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  room VARCHAR(60) NOT NULL,
  capacity SMALLINT NOT NULL DEFAULT 40,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_schedule_program FOREIGN KEY (program_id) REFERENCES programs(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_schedule_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT uq_schedule_offering UNIQUE
    (subject_id, school_year, semester, year_level, section, days, start_time),
  CONSTRAINT ck_schedule_semester CHECK (semester IN ('1st', '2nd', 'Summer')),
  CONSTRAINT ck_schedule_capacity CHECK (capacity BETWEEN 1 AND 500)
);

CREATE TABLE IF NOT EXISTS grades (
  enrollment_id INTEGER NOT NULL,
  subject_id INTEGER NOT NULL,
  preliminary NUMERIC(4,2) NULL,
  midterm NUMERIC(4,2) NULL,
  final_term NUMERIC(4,2) NULL,
  final_grade NUMERIC(4,2) NULL,
  remarks VARCHAR(20) NOT NULL DEFAULT 'In progress',
  encoded_by INTEGER NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (enrollment_id, subject_id),
  CONSTRAINT fk_grade_enrollment_subject FOREIGN KEY (enrollment_id, subject_id)
    REFERENCES enrollment_subjects(enrollment_id, subject_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_grade_encoder FOREIGN KEY (encoded_by) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT ck_grade_remarks CHECK (remarks IN ('In progress', 'Passed', 'Failed', 'Incomplete')),
  CONSTRAINT ck_grade_preliminary CHECK (preliminary IS NULL OR preliminary BETWEEN 1 AND 5),
  CONSTRAINT ck_grade_midterm CHECK (midterm IS NULL OR midterm BETWEEN 1 AND 5),
  CONSTRAINT ck_grade_final_term CHECK (final_term IS NULL OR final_term BETWEEN 1 AND 5),
  CONSTRAINT ck_grade_final CHECK (final_grade IS NULL OR final_grade BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_enrollments_status ON enrollments(status);
CREATE INDEX IF NOT EXISTS idx_enrollments_term ON enrollments(school_year, semester);
CREATE INDEX IF NOT EXISTS idx_subjects_program ON subjects(program_id);
CREATE INDEX IF NOT EXISTS idx_subjects_source ON subjects(program_id, source_id, major_id, year_level, semester);
CREATE INDEX IF NOT EXISTS idx_schedules_term ON class_schedules(school_year, semester, program_id, year_level);

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS trg_programs_updated_at ON programs;
CREATE TRIGGER trg_programs_updated_at BEFORE UPDATE ON programs
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS trg_program_majors_updated_at ON program_majors;
CREATE TRIGGER trg_program_majors_updated_at BEFORE UPDATE ON program_majors
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS trg_subjects_updated_at ON subjects;
CREATE TRIGGER trg_subjects_updated_at BEFORE UPDATE ON subjects
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS trg_enrollments_updated_at ON enrollments;
CREATE TRIGGER trg_enrollments_updated_at BEFORE UPDATE ON enrollments
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS trg_class_schedules_updated_at ON class_schedules;
CREATE TRIGGER trg_class_schedules_updated_at BEFORE UPDATE ON class_schedules
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS trg_grades_updated_at ON grades;
CREATE TRIGGER trg_grades_updated_at BEFORE UPDATE ON grades
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
