@extends('layouts.app')

@section('title', 'Program catalog')
@section('eyebrow', 'Registrar / Programs')

@section('content')
    <section class="page-heading-row"><div><p class="section-kicker">Academic offerings</p><h1 class="page-title">Program catalog<span class="title-period">.</span></h1><p class="page-lede">Manage the programs visible to students during enrollment.</p></div><details class="add-details"><summary class="button button-primary">Add a program <span aria-hidden="true">＋</span></summary><form class="add-program-form panel" method="post" action="{{ route('registrar.programs.store') }}">@csrf<label class="field-label" for="new-code">Program code</label><input class="form-control" id="new-code" name="code" value="{{ old('code') }}" placeholder="BSIT" maxlength="20" required><label class="field-label" for="new-name">Program name</label><input class="form-control" id="new-name" name="name" value="{{ old('name') }}" required><label class="field-label" for="new-department">Department</label><input class="form-control" id="new-department" name="department" value="{{ old('department', 'Buenavista Community College') }}" maxlength="120" required><label class="field-label" for="new-duration">Program length</label><select class="form-control" id="new-duration" name="duration_years">@foreach (range(1, 6) as $years)<option value="{{ $years }}">{{ $years }} years</option>@endforeach</select><button class="button button-primary button-wide" type="submit">Save program</button></form></details></section>
    <section class="panel list-panel">
        <div class="table-wrap"><table class="responsive-table programs-table"><thead><tr><th>Program</th><th>Department</th><th>Length</th><th>Subjects</th><th>Status</th><th></th></tr></thead><tbody>
            @forelse ($programs as $program)
                <tr><td><strong>{{ $program->code }}</strong><small>{{ $program->name }}</small></td><td>{{ $program->department }}</td><td>{{ $program->duration_years }} years</td><td>{{ $program->subjects_count }}</td><td><span class="status-badge {{ $program->is_active ? 'status-approved' : 'status-withdrawn' }}">{{ $program->is_active ? 'Open' : 'Archived' }}</span></td><td><details class="review-details"><summary>Manage</summary><div class="student-actions"><form class="student-edit-form" method="post" action="{{ route('registrar.programs.update', $program) }}">@csrf @method('PATCH')<label class="field-label" for="program-code-{{ $program->id }}">Program code</label><input class="form-control form-control-small" id="program-code-{{ $program->id }}" name="code" value="{{ $program->code }}" maxlength="20" required><label class="field-label" for="program-name-{{ $program->id }}">Program name</label><input class="form-control form-control-small" id="program-name-{{ $program->id }}" name="name" value="{{ $program->name }}" required><label class="field-label" for="program-department-{{ $program->id }}">Department</label><input class="form-control form-control-small" id="program-department-{{ $program->id }}" name="department" value="{{ $program->department }}" maxlength="120" required><label class="field-label" for="program-duration-{{ $program->id }}">Duration</label><select class="form-control form-control-small" id="program-duration-{{ $program->id }}" name="duration_years">@foreach (range(1, 6) as $years)<option value="{{ $years }}" @selected($program->duration_years === $years)>{{ $years }} years</option>@endforeach</select><button class="button button-primary button-small" type="submit">Save changes</button></form><form method="post" action="{{ route('registrar.programs.toggle', $program) }}">@csrf @method('PATCH')<button class="button button-quiet button-small" type="submit">{{ $program->is_active ? 'Archive program' : 'Reopen program' }}</button></form></div></details></td></tr>
            @empty
                <tr><td class="empty-cell" colspan="6">No programs are listed.</td></tr>
            @endforelse
        </tbody></table></div>
        <div class="pagination-row">{{ $programs->links() }}</div>
    </section>
@endsection
